import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  ShadingType,
  BorderStyle,
  AlignmentType,
} from "docx";
import type { TeacherReport } from "./types";

const PAGE_WIDTH_DXA = 12240;
const PAGE_HEIGHT_DXA = 15840;
const MARGIN_DXA = 1080;
const TABLE_WIDTH_DXA = PAGE_WIDTH_DXA - MARGIN_DXA * 2;
const COL_WIDTHS = [Math.round(TABLE_WIDTH_DXA * 0.3), Math.round(TABLE_WIDTH_DXA * 0.7)];

function headerCell(text: string): TableCell {
  return new TableCell({
    width: { size: COL_WIDTHS[0], type: WidthType.DXA },
    shading: { type: ShadingType.CLEAR, fill: "EDE9FE" },
    margins: { top: 100, bottom: 100, left: 120, right: 120 },
    children: [new Paragraph({ children: [new TextRun({ text, bold: true })] })],
  });
}

function bodyCell(text: string, width: number, bold = false): TableCell {
  return new TableCell({
    width: { size: width, type: WidthType.DXA },
    margins: { top: 100, bottom: 100, left: 120, right: 120 },
    children: [new Paragraph({ children: [new TextRun({ text, bold })] })],
  });
}

function buildTable(columns: string[], rows: string[][]): Table {
  return new Table({
    width: { size: TABLE_WIDTH_DXA, type: WidthType.DXA },
    columnWidths: COL_WIDTHS,
    rows: [
      new TableRow({ tableHeader: true, children: columns.map((c) => headerCell(c)) }),
      ...rows.map(
        (row) =>
          new TableRow({
            children: row.map((cell, i) => bodyCell(cell, COL_WIDTHS[i] ?? COL_WIDTHS[1], i === 0)),
          })
      ),
    ],
  });
}

function heading(text: string): Paragraph {
  return new Paragraph({
    heading: HeadingLevel.HEADING_2,
    spacing: { before: 300, after: 150 },
    children: [new TextRun({ text })],
  });
}

export async function buildReportDocx(report: TeacherReport): Promise<Buffer> {
  const { structured } = report;

  const detailsTable = buildTable(
    ["Detail", "Value"],
    [
      ["Report Type", report.reportType],
      ["Class", report.className],
      ["Subject", report.subject],
      ["Date", report.date],
      ["Submitted By", report.teacherName],
      ["Status", structured.status],
      ["Submitted On", new Date(report.submittedAt).toLocaleString()],
    ]
  );

  const summaryTable = buildTable(structured.table.columns, structured.table.rows);

  const originalParagraphs = report.reportText
    .split(/\n+/)
    .filter((line) => line.trim().length > 0)
    .map(
      (line) =>
        new Paragraph({
          bullet: { level: 0 },
          spacing: { after: 100 },
          children: [new TextRun({ text: line })],
        })
    );

  const doc = new Document({
    sections: [
      {
        properties: {
          page: {
            size: { width: PAGE_WIDTH_DXA, height: PAGE_HEIGHT_DXA },
            margin: { top: MARGIN_DXA, bottom: MARGIN_DXA, left: MARGIN_DXA, right: MARGIN_DXA },
          },
        },
        children: [
          new Paragraph({
            heading: HeadingLevel.TITLE,
            children: [new TextRun({ text: `Soul Valley SRS — ${report.reportType}` })],
          }),
          new Paragraph({
            spacing: { after: 200 },
            children: [
              new TextRun({
                text: `${report.className} — ${report.subject}`,
                bold: true,
                size: 28,
              }),
            ],
          }),

          heading("Report Details"),
          detailsTable,

          heading("Structured Summary"),
          summaryTable,

          heading("Original Submission"),
          ...(originalParagraphs.length
            ? originalParagraphs
            : [new Paragraph({ children: [new TextRun({ text: report.reportText })] })]),

          new Paragraph({
            spacing: { before: 400 },
            border: {
              top: { style: BorderStyle.SINGLE, size: 4, color: "CBD5E1" },
            },
            children: [],
          }),
          new Paragraph({
            spacing: { before: 150 },
            alignment: AlignmentType.LEFT,
            children: [
              new TextRun({
                text:
                  report.source === "ai"
                    ? "This summary was generated by AI from the original submission above, which remains the source of record."
                    : "This summary was generated automatically from the original submission above, which remains the source of record.",
                italics: true,
                size: 18,
                color: "64748B",
              }),
            ],
          }),
        ],
      },
    ],
  });

  return Packer.toBuffer(doc);
}
